language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install -r requirements.txt

script:
  - pytest

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "OHg9xaa0vZ3R0DqOnHDnvTnBAbg7m4C4ABGlmRbkM41up9phAXYudiYOc9UDu0O+C4oXaGCihzQ2o5upcTjWOw3INwsCtOBw8+/F4OD1KVLR6lzuDgBdztil19mwBlUksCeDysntDgoXHkGjTM4sWKom7Xe0YMh5rNSbGIte7QRA4+YPVhYMmndi1y6ELvpCZMX+GNeUkiXqncShXVi/Afn8iU/KzEKl0cbhtfIEfSBTxnVCIYv8wULdCGKgb7ZrcY91G5t777Ds+tY9qtPGh6mykCpYBDOOmZXYSyBolVa7EncdaF8rx2ylbEYtT2oxPx+5Xbv+J3O7ChPqhyHhYrTa6hw481ta9DEyBjK/pBENVoPRnZsdE2FQkCsA3GTh93qgZ7nDU0JlvHpX09LKQICc/Fk0z5AvPXv9xw73vGs1uISaImtijcCq60F3mPTuh/37OEcvfNPxQQsvNzPfr1xOqNgCvLDi9fqz6v/1jMHNwI+AvWwsP3lgnYXz8ZhagIgnsmTcFJ1cJ82IovPMsiZKBX30QwbZLw9r2HCBM+LaSFsPgum4rUJAi8AFxOT0kPa3gH01sReq4f9Pi4Xl3+FVkMwQrDMiwbOSSSZIc0TbWYBvXsHgLKnN5ydaPjiFxt+Sm1kvlz7n/mu7mbgfyG2hgcDXTbe7+3dI4O8L+LA="
  secret_access_key:
    secure: "rukkB9X85gJIrkWOMQW8W2DwZcd5XpA0q8jWU1wprcmTCFL9EOQdsLT17PTr/9l8m3xvLWFv5WNqCYushZa5fv4UV6wJaiBH/yLba9toMzc+FyrRoG8MQ5EszfA4hAxEDDAf1nPICTm6dqrxHLCIOf4pAE7qOAq0CwVjZQjNr4GRqx2yf/0fDeXSdp8H8P5KcPdY4aBHVfHWuRpwvf79Vl3ueM+eQ2OK/u5coxMoBShhBPU6pTgFN37mhZlbLCf03TXuKcFmFNOC6Q4edcO9Tu0BdI7fuaCDvnd+VtG9BZmeVYn1QLXgaxJTcvfC+aoXghMlv6V8ehcxMmeklTQom3l8/p+9Va1CdBvi48JJ7vYvts88kD0B78OyMMDqYQio9EuH+bFAVkoWvDQXig33VCChH1l9dDpfR6f+5/rRu6BMiERcfa0dZ+pEEt8ukDVQYHgvTKqTeR1LKLLYvQXNLXGpbDcjHlsnXIo3XR1GM9oxm37bI//+aEKLzXHihq1phYTASyRfHfKGnb+rWwIrtsDOQ28OJ2dche7N0v1ssM9/6E9PPBt8JRMFMzLouanLvPTHsniuc3noxvt/9l2u056hOYQur3bi5zjhvBAXoKrQNA2lyfctDWA03WPESZ0LtbkXdiuZmlaBc5hzABjo2alIqdVD0Io5uXJpl46PUMM="
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-049461798922"